# SPDX-License-Identifier: GPL-2.0

# Makefile for the accel framework. This framework provides support for
# compute acceleration devices, such as, but not limited to, Machine-Learning
# and Deep-Learning acceleration devices

obj-$(CONFIG_ACCEL_DUMMY)		+= dummy/